version: '2'
services:
  db2backup:
    image: bitnami/postgresql:14.3.0-debian-11-r4
    environment:
      - POSTGRESQL_DATABASE=hackattic
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=secretpassword
    volumes:
      - ./pgdata/my_init_script.sh:/docker-entrypoint-initdb.d/my_init_script.sh
    networks:
      default:
  endpoints:
    build: ./endpoints
    container_name: endpoints
    environment:
      - PGPASSWORD=secretpassword
      - GZIP=-Z9
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - 5000:5000
    networks:
      default:
  backuprestore:
    image: python:3.7-alpine
    command: /bin/sh -c "while true; do sleep 365d; done"
networks:
  default:
