version: '2'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  endpoints:
    build: ./endpoints
    container_name: endpoints
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - 5000:5000
    networks:
      default:
  backuprestore:
    image: python:3.7-alpine
    command: python
networks:
  default:
