version: '2.1'
services:
  db2backup:
    image: bitnami/postgresql:14.3.0-debian-11-r4
    environment:
      - POSTGRESQL_DATABASE=${PGDATABASE}
      - POSTGRESQL_USERNAME=${PGUSER}
      - POSTGRESQL_PASSWORD=${PGPASSWORD}
    volumes:
      - ./pgdata/my_init_script.sh:/docker-entrypoint-initdb.d/my_init_script.sh
    networks:
      backend:
  db2restore:
    image: bitnami/postgresql:14.3.0-debian-11-r4
    environment:
      - POSTGRESQL_DATABASE=${PGDATABASE}
      - POSTGRESQL_USERNAME=${PGUSER}
      - POSTGRESQL_PASSWORD=${PGPASSWORD}
    networks:
      backend:
  endpoints:
    build: ./endpoints
    container_name: endpoints
    environment:
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - GZIP=${GZIP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP}
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    networks:
      backend:
  backuprestore:
    image: alpine:3.16.0
    environment:
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - FLASK_PORT:${FLASK_PORT}
    command: ["/backupandrestore.sh"]
    networks:
      backend:
    volumes:
      - ./backupandrestore.sh:/backupandrestore.sh

networks:
  backend:
