version: '2'
services:
  db2backup:
    image: bitnami/postgresql:14.3.0-debian-11-r4
    environment:
      - POSTGRESQL_DATABASE=${PGDATABASE}
      - POSTGRESQL_USERNAME=${PGUSER}
      - POSTGRESQL_PASSWORD=${PGPASSWORD}
    volumes:
      - ./pgdata/my_init_script.sh:/docker-entrypoint-initdb.d/my_init_script.sh
    networks:
      default:
  endpoints:
    build: ./endpoints
    container_name: endpoints
    environment:
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - GZIP=${GZIP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP}
    ports:
      - 5000:5000
    networks:
      default:
  backuprestore:
    image: python:3.7-alpine
    command: /bin/sh -c "while true; do sleep 365d; done"
networks:
  default:
